### PR TITLE
Fixed an issue where upwards resolved schematics would break schem list

### LINKED ISSUE #1475: //schematic list breaks when using ../../ to store schematic files
**Versions**

WorldEdit version: worldedit-bukkit-7.1.0
Platform version: Paper version git-Paper-385 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**Describe the bug**
In the config when using ../../folder to store schematics, creating and loading schematics works fine, but it's not able to get the schematic list

**To Reproduce**

1. Go to the world edit config, and set the schematics folder to ../../schematics
2. Create a new folder in the server root folder called schematics
3. Boot up your server, create a schematic, and type //schematic list

**Expected behavior**

It should give you a list what schematics are stored

**Screenshots**

[Error code in console](https://i.mrstefan.art/cIBqCk2Fxq.png)

**Additional context**

[01:09:43 ERROR]: Uncaught exception occurred in task: null
java.lang.ArrayIndexOutOfBoundsException: 1
        at com.sk89q.worldedit.command.SchematicCommands$SchematicPaginationBox.getComponent(SchematicCommands.java:439) ~[?:?]
        at com.sk89q.worldedit.util.formatting.component.PaginationBox.create(PaginationBox.java:91) ~[?:?]
        at com.sk89q.worldedit.command.SchematicCommands$SchematicListTask.call(SchematicCommands.java:400) ~[?:?]
        at com.sk89q.worldedit.command.SchematicCommands$SchematicListTask.call(SchematicCommands.java:356) ~[?:?]
        at com.sk89q.worldedit.command.util.AsyncCommandBuilder.runTask(AsyncCommandBuilder.java:139) ~[?:?]
        at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:111) ~[patched_1.15.2.jar:git-Paper-385]
        at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:58) ~[patched_1.15.2.jar:git-Paper-385]
        at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:75) ~[patched_1.15.2.jar:git-Paper-385]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_251]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_251]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
>

### PR DESCRIPTION
**Pull request by me4502**
I've also cleaned up a bit of code, making it use NIO rather than the old File class

We now use the actual paths rather than relying on hacky logic.

Fixes #1475

### CODE REVIEW

File: worldedit-core/src/main/java/com/sk89q/worldedit/WorldEdit.java [hunk 1]
```diff
@@ -427,13 +427,25 @@ public void checkMaxBrushRadius(double radius) throws MaxBrushRadiusException {
      * @param path the subpath under the working directory
      * @return a working directory
      */
+    @Deprecated
```
Comment (octylFractal) [inline worldedit-core/src/main/java/com/sk89q/worldedit/WorldEdit.java:430]: Document replacement in `@deprecated`?

File: worldedit-core/src/main/java/com/sk89q/worldedit/command/SchematicCommands.java [hunk 2]
```diff
@@ -353,95 +351,97 @@ public Void call() throws Exception {
...
-            File file = files[number];
-            Multimap<String, ClipboardFormat> exts = ClipboardFormats.getFileExtensionMap();
-            String format = exts.get(Files.getFileExtension(file.getName()))
-                    .stream().findFirst().map(ClipboardFormat::getName).orElse("Unknown");
-            boolean inRoot = file.getParentFile().getName().equals(prefix);
+            checkArgument(number < files.size() && number >= 0);
+            Path file = files.get(number);
+
+            String format = ClipboardFormats.getFileExtensionMap()
+                .get(com.google.common.io.Files.getFileExtension(file.getFileName().toString()))
```
Comment (octylFractal) [inline worldedit-core/src/main/java/com/sk89q/worldedit/command/SchematicCommands.java:434]:
```suggestion
                .get(MoreFiles.getFileExtension(file))
```
Guava is cool :P

File: worldedit-forge/src/main/java/com/sk89q/worldedit/forge/ForgeConfiguration.java [hunk 3]
```diff
@@ -22,14 +22,15 @@
...
+import java.nio.file.Path;
 
 public class ForgeConfiguration extends PropertiesConfiguration {
 
     public boolean creativeEnable = false;
     public boolean cheatMode = false;
 
     public ForgeConfiguration(ForgeWorldEdit mod) {
-        super(new File(mod.getWorkingDir() + File.separator + "worldedit.properties"));
+        super(mod.getWorkingDir().resolve("worldedit.properties").toFile());
```
Comment (octylFractal) [inline worldedit-forge/src/main/java/com/sk89q/worldedit/forge/ForgeConfiguration.java:33]: Maybe just add a new `PropertiesConfiguration` constructor?

File: worldedit-core/src/main/java/com/sk89q/worldedit/util/PropertiesConfiguration.java [hunk 4]
```diff
@@ -57,12 +58,23 @@
      *
      * @param path the path tot he configuration
```
Comment (octylFractal) [inline worldedit-core/src/main/java/com/sk89q/worldedit/util/PropertiesConfiguration.java:59]: Fix typo while you're here? :P
```suggestion
     * @param path the path to the configuration
```

File: worldedit-core/src/main/java/com/sk89q/worldedit/util/PropertiesConfiguration.java [hunk 5]
```diff
@@ -57,12 +58,23 @@
...
+    public PropertiesConfiguration(Path path) {
+        this.path = path.toFile();
 
         properties = new Properties();
     }
 
+    /**
+     * Construct the object. The configuration isn't loaded yet.
+     *
+     * @param path the path tot he configuration
```
Comment (octylFractal) [inline worldedit-core/src/main/java/com/sk89q/worldedit/util/PropertiesConfiguration.java:70]:
```suggestion
     * @param path the path to the configuration
```
